#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=10gb,walltime=0:10:00
#PBS -N workbench-test
#PBS -V

module unload matlab
module load matlab/2017a

export LD_LIBRARY_PATH=/N/u/davhunt/Carbonate/workbench/libs_rh_linux64:/N/u/davhunt/Carbonate/workbench/libs_rh_linux64_software_opengl:/N/soft/rhel7/matlab/MATLAB_Compiler_Runtime/v92/runtime/glnxa64:/N/soft/rhel7/matlab/MATLAB_Compiler_Runtime/v92/bin/glnxa64:/N/soft/rhel7/matlab/MATLAB_Compiler_Runtime/v92/sys/os/glnxa64:$LD_LIBRARY_PATH

time singularity exec -e -w docker://davhunt/wb_freesurfer:3.0 ./compiled/main
